# version: '3.4'

services:
#   localdocker:
#     image: localdocker
#     build:
#       context: .
#       dockerfile: ./Dockerfile
  nginx:
    image: nginx:1.26
    ports:
      - "80:80"
    volumes:
      - F:\wsl\lnmp\nginx\log\laravelgame.log:/usr/local/game/laravelgame.log;
      - F:\wsl\lnmp\nginx\log\laravellanguage.log:/usr/local/game/laravellanguage.log;
      - F:\wsl\lnmp\nginx\rewrite\laravel.conf:/etc/nginx/rewrite/laravel.conf
      - F:\wsl\lnmp\nginx\enable-php-pathinfo.conf:/etc/nginx/enable-php-pathinfo.conf
      - F:\wsl\lnmp\nginx\nginx.conf:/etc/nginx/nginx.conf
      - F:\wsl\lnmp\nginx\conf.d:/etc/nginx/conf.d
      - E:\www:/usr/share/nginx/html/
      - F:\wsl\lnmp\nginx\conf.d\www.laravelgame.com.conf:/etc/nginx/conf.d/www.laravelgame.com.conf
      - F:\wsl\lnmp\nginx\conf.d\www.laravellanguage.com.conf:/etc/nginx/conf.d/www.laravellanguage.com.conf
    depends_on:
      - php8.0
      - mysql8.0
      
  php8.0:
    image: php:8.0
    ports:
      - "9000:9000"
    volumes:
      - F:\wsl\lnmp\php\php-fpm.conf:/usr/local/etc/php-fpm.conf
      - F:\wsl\lnmp\php\pear.conf:/usr/local/etc/pear.conf
      - F:\wsl\lnmp\php\php\php.ini:/usr/local/etc/php/php.ini
      - F:\wsl\lnmp\php\php\docker-fpm.ini:/usr/local/etc/php/docker-fpm.ini
      - F:\wsl\lnmp\php\php\docker-php-ext-pdo_mysql.ini:/usr/local/etc/php/docker-php-ext-pdo_mysql.ini
      - F:\wsl\lnmp\php\php\docker-php-ext-sodium.ini:/usr/local/etc/php/docker-php-ext-sodium.ini
      - E:\www:/usr/share/nginx/html
    depends_on:
      - mysql8.0
      - redis

  mysql8.0:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - F:\wsl\lnmp\mysql\data:/var/lib/mysql

  redis:
    image: redis:7.4.2-bookworm
    ports:
      - "6379:6379"
    volumes:
      - F:\wsl\lnmp\redis\redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: my_network  # 添加固定网络名称
    external: false   # 设置为 false 表示由 Docker Compose 管理


